[package]
name = "weaveling-projects-store"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
sqlx = { workspace = true, optional = true }
time = { workspace = true }

projects-core = { version = "0.1.0", path = "../../core", package = "weaveling-projects-core" }

[features]
postgres = ["dep:sqlx"]

[dev-dependencies]
time = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
test-harness = { version = "0.1.0", path = "../../../../libraries/test-harness", package = "weaveling-test-harness" }
