[package]
name = "weaveling-projects-store"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }

projects-core = { version = "0.1.0", path = "../../core", package = "weaveling-projects-core" }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

projects-core = { version = "0.1.0", path = "../../core", package = "weaveling-projects-core", features = ["testkit"] }
