[package]
name = "weaveling-projects-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
projects-core = { version = "0.1.0", path = "../../core", package = "weaveling-projects-core" }

[dev-dependencies]
projects-core = { version = "0.1.0", path = "../../core", package = "weaveling-projects-core", features = ["testkit"] }
tokio = { workspace = true, features = ["rt", "macros"] }
