[package]
name = "weaveling-pieces-catalog"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
time = { workspace = true }

eventsourcing = { version = "0.1.0", path = "../../../../libraries/eventsourcing", package = "weaveling-eventsourcing" }

pieces-core = { version = "0.1.0", path = "../../core", package = "weaveling-pieces-core" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
