[package]
name = "weaveling-pieces-rest"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
tracing = { workspace = true }

eventsourcing = { version = "0.1.0", path = "../../../../libraries/eventsourcing", package = "weaveling-eventsourcing" }
pieces-contract = { version = "0.1.0", path = "../../contract", package = "weaveling-pieces-contract" }
pieces-core = { version = "0.1.0", path = "../../core", package = "weaveling-pieces-core" }
