[package]
name = "weaveling-client-web"
version.workspace = true
edition.workspace = true

[dependencies]
console_error_panic_hook = { workspace = true }
gloo-net = { workspace = true }
leptos = { workspace = true, features = ["csr"] }
leptos_router = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = [
    "Element",
    "History",
    "HtmlElement",
    "Location",
    "UrlSearchParams",
    "Window",
] }
time = { workspace = true, features = [
    "parsing",
    "formatting",
    "macros",
    "local-offset",
    "wasm-bindgen",
] }

boards-contract = { version = "0.1.0", path = "../../features/boards/contract", package = "weaveling-boards-contract" }
pieces-contract = { version = "0.1.0", path = "../../features/pieces/contract", package = "weaveling-pieces-contract" }
passages-contract = { version = "0.1.0", path = "../../features/passages/contract", package = "weaveling-passages-contract" }
projects-contract = { version = "0.1.0", path = "../../features/projects/contract", package = "weaveling-projects-contract" }
