[package]
name = "weaveling-ideas-wiring"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = { workspace = true, optional = true }

wiring = { version = "0.1.0", path = "../../../libraries/wiring", package = "weaveling-wiring" }


clock = { version = "0.1.0", path = "../../../libraries/clock", package = "weaveling-clock" }
messaging = { version = "0.1.0", path = "../../../libraries/messaging", package = "weaveling-messaging" }
eventsourcing = { version = "0.1.0", path = "../../../libraries/eventsourcing", package = "weaveling-eventsourcing" }

ideas-core = { version = "0.1.0", path = "../core", package = "weaveling-ideas-core" }
ideas-messaging = { version = "0.1.0", path = "../adapters/messaging", package = "weaveling-ideas-messaging" }
ideas-rest = { version = "0.1.0", path = "../adapters/rest", package = "weaveling-ideas-rest" }
ideas-catalog = { version = "0.1.0", path = "../adapters/catalog", package = "weaveling-ideas-catalog" }
ideas-store = { version = "0.1.0", path = "../adapters/store", package = "weaveling-ideas-store" }

[features]
postgres = ["dep:sqlx", "wiring/postgres", "eventsourcing/postgres", "ideas-catalog/postgres"]
