[package]
name = "weaveling-passages-store"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }

passages-core = { version = "0.1.0", path = "../../core", package = "weaveling-passages-core" }

[dev-dependencies]
time = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
yrs = { workspace = true }
