[package]
name = "weaveling-projects-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
testkit = []

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
