[package]
name = "weaveling-boards-rest"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

eventsourcing = { version = "0.1.0", path = "../../../../libraries/eventsourcing", package = "weaveling-eventsourcing" }
serving = { version = "0.1.0", path = "../../../../libraries/serving", package = "weaveling-serving" }

boards-contract = { version = "0.1.0", path = "../../contract", package = "weaveling-boards-contract" }
boards-core = { version = "0.1.0", path = "../../core", package = "weaveling-boards-core" }
