[package]
name = "weaveling-service-api"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net"] }
tower-http = { workspace = true, features = ["trace", "fs"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

#################
### LIBRARIES ###
#################

clock = { version = "0.1.0", path = "../../libraries/clock", package = "weaveling-clock" }
messaging = { version = "0.1.0", path = "../../libraries/messaging", package = "weaveling-messaging" }

################
### FEATURES ###
################

boards-wiring = { version = "0.1.0", path = "../../features/boards/wiring", package = "weaveling-boards-wiring" }

passages-wiring = { version = "0.1.0", path = "../../features/passages/wiring", package = "weaveling-passages-wiring" }

pieces-wiring = { version = "0.1.0", path = "../../features/pieces/wiring", package = "weaveling-pieces-wiring" }

projects-wiring = { version = "0.1.0", path = "../../features/projects/wiring", package = "weaveling-projects-wiring" }

[dev-dependencies]
tower = { workspace = true }
