[package]
name = "weaveling-boards-wiring"
version.workspace = true
edition.workspace = true

[dependencies]
wiring = { version = "0.1.0", path = "../../../libraries/wiring", package = "weaveling-wiring" }


clock = { version = "0.1.0", path = "../../../libraries/clock", package = "weaveling-clock" }
eventsourcing = { version = "0.1.0", path = "../../../libraries/eventsourcing", package = "weaveling-eventsourcing" }

boards-core = { version = "0.1.0", path = "../core", package = "weaveling-boards-core" }
boards-rest = { version = "0.1.0", path = "../adapters/rest", package = "weaveling-boards-rest" }
boards-messaging = { version = "0.1.0", path = "../adapters/messaging", package = "weaveling-boards-messaging" }
boards-catalog = { version = "0.1.0", path = "../adapters/catalog", package = "weaveling-boards-catalog" }
