[package]
name = "weaveling-messaging"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
uuid = { workspace = true, features = ["v7"] }

ids = { version = "0.1.0", path = "../ids", package = "weaveling-ids" }
