[package]
name = "weaveling-passages-wiring"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = { workspace = true, optional = true }

wiring = { version = "0.1.0", path = "../../../libraries/wiring", package = "weaveling-wiring" }


clock = { version = "0.1.0", path = "../../../libraries/clock", package = "weaveling-clock" }
messaging = { version = "0.1.0", path = "../../../libraries/messaging", package = "weaveling-messaging" }
eventsourcing = { version = "0.1.0", path = "../../../libraries/eventsourcing", package = "weaveling-eventsourcing" }

passages-core = { version = "0.1.0", path = "../core", package = "weaveling-passages-core" }
passages-rest = { version = "0.1.0", path = "../adapters/rest", package = "weaveling-passages-rest" }
passages-sync = { version = "0.1.0", path = "../adapters/sync", package = "weaveling-passages-sync" }
passages-store = { version = "0.1.0", path = "../adapters/store", package = "weaveling-passages-store" }

[features]
postgres = ["dep:sqlx", "wiring/postgres", "eventsourcing/postgres", "passages-store/postgres"]
