[package]
name = "weaveling-eventsourcing"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }

serde_json = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }

clock = { version = "0.1.0", path = "../clock", package = "weaveling-clock" }

[features]
postgres = ["dep:serde_json", "dep:sqlx"]

[dev-dependencies]
serde = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

test-harness = { version = "0.1.0", path = "../test-harness", package = "weaveling-test-harness" }
