[package]
name = "weaveling-eventsourcing"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }

clock = { version = "0.1.0", path = "../clock", package = "weaveling-clock" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
